'use strict';

export const TEST = '/';
export const FETCH_TESTRUN_LIST='FETCH_TESTRUN_LIST';
export const RECEIVE_TESTRUN_LIST='RECEIVE_TESTRUN_LIST';
export const CHANGE_TESTRUN_INFO='CHANGE_TESTRUN_INFO';
export const CHANGE_TESTSUITE_INFO='CHANGE_TESTSUITE_INFO';
export const CHANGE_TESTCASE_INFO='CHANGE_TESTCASE_INFO';
export const CHANGE_SNACKBAR_INFO='CHANGE_SNACKBAR_INFO';
export const CHANGE_SNACKBAR_SHOW_INFO='CHANGE_SNACKBAR_SHOW_INFO';
